version: '3'

services:
  
  php:
    image: benboit/sw6-docker-php:7.2
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www"

  cli:
    image: benboit/sw6-docker-php:7.2-cli
    ports:
      - "9100:9000"
    volumes:
      - "./:/var/www"
  
  nginx:
    image: benboit/sw6-docker-nginx:1.14
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/var/www"

  mysql:
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"

  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"