version: '3'

services:
  
  php:
    image: benboit/sw6-docker-php:7.2
    ports:
      - "9000:9000"
    volumes:
      - "./www:/var/www"
  
  nginx:
    image: benboit/sw6-docker-nginx:1.14
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./www:/var/www"

  mysql:
    image: mariadb:10.3
    ports:
     - "3306:3306"

  redis:
    image: 4.0-alpine
    ports:
     - "6379:6379"

  elasticsearch:
    image: 5.6-alpine
    ports:
      - "9200:9200"
      - "9300:9300"